const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUp";
const String HomeViewRoute = "HomeView";
const String CreateProductViewRoute = "CreateProductView";
const String ProductDetailRoute = "ProductDetailView";
const String CreateOrderViewRoute = "CreateOrderView";
const String CreateStockViewRoute = "CreateStockView";
const String CreateInvoiceViewRoute = "CreateInvoiceView";
// Generate the views here